apiVersion: v1
kind: Secret
metadata:
  name: tododb-secret
type: Opaque
#here, instead of stringData we may use data and encoded base64 values. for the sake of simplicity we used stringData
stringData:
  MYSQL_ROOT_PASSWORD: abrakadabra
  MYSQL_DATABASE: TASKDB
  MYSQL_USER: taskuser
  MYSQL_PASSWORD: taskpass
---
#This will work with redhat sandbox environment. if you run this on another platform use another SC or use hostPath
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  #for auto provisioning of PVs we will need a SC. write it here..
  storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
# we selected statefulset as the type. It is more approprite for persistent data storage needs
kind: StatefulSet
metadata:
  labels:
    app: tododb
  name: tododb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tododb
  
  template:
    metadata:
      labels:
        app: tododb
    spec:
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      containers:
      #normally we do not need to specify docker.io. but if we run it redhat sandbox, it defaults to quay.io and we need to specify it.
      - image: docker.io/mariadb:10.7
        name: tododb
        volumeMounts:
        - name: mysql-persistent-storage
          #here is the default dir. where mariadb wrtes its db files..
          mountPath: /var/lib/mysql
        #we mount secrets as env variables and inside our app, we initialize our variables from shell environment
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tododb-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: tododb-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tododb-secret
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: tododb-secret
              key: MYSQL_DATABASE


---

apiVersion: v1
kind: Service
metadata:
   name: taskdb
spec:
  ports:
  - port: 3306
  selector:
    app: tododb
  #this is a headless service. so clusterIP will be none. communicaton goes with DNS records not clusterIP..
  clusterIP: None
   